
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PuntoPunto = 48;
  public static final int OperadorDiferente = 10;
  public static final int Begin = 27;
  public static final int PuntoComa = 50;
  public static final int Coma = 39;
  public static final int BracketCerrar = 38;
  public static final int OperadorMayor = 11;
  public static final int OperadorDivisionSpecial = 23;
  public static final int End = 28;
  public static final int Until = 34;
  public static final int Repeat = 33;
  public static final int If = 24;
  public static final int DosPuntosIgual = 41;
  public static final int Of = 3;
  public static final int Var = 4;
  public static final int ParentesisCerrar = 44;
  public static final int Else = 26;
  public static final int Read = 36;
  public static final int Then = 25;
  public static final int Punto = 49;
  public static final int OperadorOr = 16;
  public static final int While = 32;
  public static final int To = 30;
  public static final int TipoInteger = 7;
  public static final int For = 29;
  public static final int EOF = 0;
  public static final int DosPuntos = 40;
  public static final int OperadorAnd = 15;
  public static final int OperadorNot = 17;
  public static final int Function = 47;
  public static final int error = 1;
  public static final int LiteralCaracter = 52;
  public static final int ParentesisAbrir = 43;
  public static final int OperadorResta = 19;
  public static final int Do = 31;
  public static final int LiteralString = 54;
  public static final int OperadorIgual = 9;
  public static final int OperadorMod = 21;
  public static final int TipoBoolean = 5;
  public static final int Identificador = 42;
  public static final int OperadorMenorIgual = 14;
  public static final int Array = 2;
  public static final int TipoChar = 6;
  public static final int OperadorSuma = 18;
  public static final int Write = 35;
  public static final int OperadorMultiplicacion = 20;
  public static final int Program = 45;
  public static final int BracketAbrir = 37;
  public static final int LiteralEntero = 51;
  public static final int OperadorDivision = 22;
  public static final int TipoString = 8;
  public static final int OperadorMayorIgual = 13;
  public static final int Procedure = 46;
  public static final int OperadorMenor = 12;
  public static final int LiteralBoolean = 53;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Array",
  "Of",
  "Var",
  "TipoBoolean",
  "TipoChar",
  "TipoInteger",
  "TipoString",
  "OperadorIgual",
  "OperadorDiferente",
  "OperadorMayor",
  "OperadorMenor",
  "OperadorMayorIgual",
  "OperadorMenorIgual",
  "OperadorAnd",
  "OperadorOr",
  "OperadorNot",
  "OperadorSuma",
  "OperadorResta",
  "OperadorMultiplicacion",
  "OperadorMod",
  "OperadorDivision",
  "OperadorDivisionSpecial",
  "If",
  "Then",
  "Else",
  "Begin",
  "End",
  "For",
  "To",
  "Do",
  "While",
  "Repeat",
  "Until",
  "Write",
  "Read",
  "BracketAbrir",
  "BracketCerrar",
  "Coma",
  "DosPuntos",
  "DosPuntosIgual",
  "Identificador",
  "ParentesisAbrir",
  "ParentesisCerrar",
  "Program",
  "Procedure",
  "Function",
  "PuntoPunto",
  "Punto",
  "PuntoComa",
  "LiteralEntero",
  "LiteralCaracter",
  "LiteralBoolean",
  "LiteralString"
  };
}

