PROGRAM FREQ<INPUT,OUTPUT);
VAR
    FREQUENCY: REAL;
    RANGE : STRINGL123 ;
BEGIN
    WRITE('++TYPE FREQUENCY: ' );
    READLN(FREQUENCY),

    RANGE := 'OUT OF RANGE';
    IF FREQUENCY <= 400 THEN 
        WRITELN('FREQUENCY TOO LOW');
    ELSE IF FREQUENCY > 20000 THEN 
        WRITELN('FREQUENCY TOO HIGH');
    ELSE IF FREQUENCY > 4000 THEN 
        RANGE := 'HIGH RANGE';
    ELSE RANGE := 'MEDIUM RANGE' ï

    WRITELN('FREQUENCY =', FREQUENCY:6:1, ' RANGE = ', RANGE );

    RANGE := 'OUT OF RANGE' ;

    (*Alternative*)
    IF FREQUENCY > 400 THEN
        IF FREQUENCY > 4000 THEN
            IF FREQUENCY > 20000 THEN
                WRITELN( 'FREQUENCY TOO HIGH' )
            ELSE RANGE : = 'HIGH RANGE'
        ELSE RANGE := 'MEDIUM RANGE'
    ELSE WRITELN('FREQUENCY TOO LOW ) ",

    WRITELN('FREQUENCY =', FREQUENCY:6:1, ' RANGE = ', RANGE );
END. 